version: "3.7"

services:
  # Base image, to be extended by user-specific services
  # Defines build configuration and basic runtime environment
  jupyterlab:
    image: criu-jupyterlab-standalone:0.4.1
    build:
      context: .
      args:
        JUPYTER_WORKDIR: /home/jovyan/work
        HTTP_PROXY: ${HTTP_PROXY}
        HTTPS_PROXY: ${HTTPS_PROXY}
    restart: on-failure
